### ISSUE TITLE
Member Profile TODO

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#597]
This is taken from #591. These can probably be broken down into separate issues @roryaronson, thoughts?

* [ ] Try deleting a Guide. It deletes it successfully but redirects the page to an error
* [ ] The devise/registrations/edit partial doesn't work. Try uncommenting it and you'll see
* [ ] /guides/index isn't there anymore. Should we stub out something for Rails convention sake or should we redirect to the profile page?
* [ ] Make the new 'Add Garden' button work and remove old confusing foo (lookout on Slack for a mockup of member signup flow)
* [ ] Displaying member badges
* [ ] Allow members to have a favorite_crop in the user_settings and display that Crop's image as their cover photo
* [ ] Allow members to upload a profile photo, and make/select a default one that isn't a barren field
* [ ] Follower/Following/Follow buttons? Explore/cinform what this concept even does and if we/members want such a thing
* [ ] Privacy controls
* [ ] Enable editing of the member profile

**Comment by simonv3** [comment]
devise/registrations/edit isn't a partial. It's meant to be the page for editing your user account.

**Comment by simonv3** [comment]
@roryaronson I think follow/ following is too much complexity for now.

**Comment by roryaronson** [comment]
Agreed. Followers/Following needs a lot of brainstorming first, and probably some type of activity notifications feature before it is useful. I'll break these up into some separate issues
