### ISSUE TITLE
Guide Editing Checklist

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/OpenFarm#722]
*Guide*
- [ ] Name
- [ ] Cover (featured) image
- [ ] Overview Text
- [ ] Add Guide Properties
- [ ] Remove Guide Properties
- [ ] Delete Guide

*Stages*
- [ ] Adding (from none)
- [ ] Adding more
- [ ] Removing some (but not all)
- [ ] Removing all

**Stage Overview Text**
- [ ] Adding (from nothing)
- [ ] Removing (completely)
- [ ] Editing

**Stage Overview Images**
- [ ] Adding (from none)
- [ ] Adding more
- [ ] Removing some (but not all)
- [ ] Removing all

**Stage Overview Properties (Soil, Light, Environment)**
- [ ] Adding (from none)
- [ ] Adding more
- [ ] Removing some (but not all)
- [ ] Removing all

*Stage Actions*
- [ ] Adding (from none)
- [ ] Adding more
- [ ] Removing some (but not all)
- [ ] Removing all

**Stage Actions Text**
- [ ] Adding (from nothing)
- [ ] Removing (completely)
- [ ] Editing

**Stage Actions Images**
- [ ] Adding (from none)
- [ ] Adding more
- [ ] Removing some (but not all)
- [ ] Removing all

**Stage Actions Properties**
- [ ] Add Time
- [ ] Edit Time
- [ ] Remove Time

**Comment by simonv3** [comment]
Oof, this is awesome!
