### ISSUE TITLE
Search page creation > Search bar

### ISSUE THREAD

**Issue by sophiakc** [openfarmcc/OpenFarm#875]
[See all tasks from Search page creation](https://github.com/openfarmcc/OpenFarm/issues/874)
[See mockup](https://www.figma.com/file/BTggnDJaZRx7YliKHUTjBu/website-2-search-page)

![search bar](https://cloud.githubusercontent.com/assets/3863675/21166893/87cf6dd4-c15d-11e6-98cb-67d74a6a3a0d.png)

Search bar composed of:
* [ ] Text field #1: All crops
e.g. tomato and display guides related to the crop tomato
* [ ] Text field #2: Current month by default
* [ ] Text field #3: Climate zone: enable auto-location
![know your location](https://cloud.githubusercontent.com/assets/3863675/21166935/c6356c54-c15d-11e6-9201-ec39d3317b83.png)
*[ ] Stages: ALL by default

**Comment by nicholasedwards** [comment]
Here is some front-end code for this that is outside of the context of the entire application: https://gist.github.com/nicholasedwards/c438d1fd1f06b4033e29c8ad1a9baf90

Next steps would be to tie that markup into the application markup and set up the inputs as search result filters (probably with Angular).

I am unassigning myself from this for now in order to focus on learning Javascript and Angular for a while (unless a JS guru wants to collaborate with me on this, in which case, let's go for it and I'll keep working on layout and styling!)

**Comment by simonv3** [comment]
@nicholasedwards I would be more than happy to help you out with implementing this in JS. Let me know if you want to set up a pair programming session or something similar. The HTML looks great, and it should be fairly straightforward to tie it into some things.

**Comment by nicholasedwards** [comment]
@simonv3 awesome. PM'd you on Slack.

**Comment by sophiakc** [comment]
hey @nicholasedwards, keep us posted here how the pair programming goes with @simonv3 :-)

**Comment by simonv3** [comment]
We're scheduled to do our session tomorrow!

**Comment by sophiakc** [comment]
@simonv3 How was it?

**Comment by simonv3** [comment]
@sophiakc it was good. You can see the work we did here: https://github.com/openfarmcc/OpenFarm/commit/afca35d3311f17fcb7ef4548980c590c29785d82

It's not finished yet. We're going to touch base on when we can do some more work together.
